.PHONY: install

install:
	@git clone https://github.com/OpceanAI/Archan-Open-source- && cd Archan-Open-source-
	@docker-compose up --build -d
	@docker-compose down --volumes

run:
	@docker-compose up -d